name: Catalog-Application-CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
#
#--- next commands can be launch separately, one after another ---
#
#    - name: Run Flake8
#      run: |
#        flake8 .
#    - name: Run Black
#      run: |
#        black --skip-string-normalization --line-length 120 --check --diff --color .
#    - name: Run Tests
#      run: |
#        python manage.py test
#
#--- or togather by the tox app
#
    - name: Run Tox (flake8 + black + tests)
      run: |
        tox
